### ISSUE TITLE
SMBv1 Incorrectly detect as enabled on Windows Server 2022

### ISSUE THREAD

**Issue by Destarianon** [Merola132/ADxRay#5]
It appears that SMBv1 is being incorrectly detected an "enabled" in reports, when run against a Windows Server 2022 domain controller.

Getting SMB protocol information via Powershell confirms it is disabled:
```
PS> Get-SmbServerConfiguration | Select EnableSMB1Protocol

EnableSMB1Protocol
------------------
             False
```
![image](https://github.com/ClaudioMerola/ADxRay/assets/6621236/e999fa15-8a48-4b7d-b727-e50f18ecd2b8)

**Comment by ClaudioMerola** [comment]
Hello @Destarianon 

You are right, it was a bug, I believe I have fixed it. Can you try the script now? (version 6.0.5)

**Comment by gitgoodgreghub** [comment]
Hello, I have the new version 6.0.5 but am still experiencing this issue.

**Comment by ClaudioMerola** [comment]
Hi @gitgoodgreghub, 

This happens only with Windows Servers 2022?

Can you open powershell in any of the servers and run the following commands and post the output here?

$TempVariable = Get-SmbServerConfiguration | Select EnableSMB1Protocol
Write-Host $TempVariable

**Comment by gitgoodgreghub** [comment]
I will try to verify that for you and get back to you as soon as I can. Also of note, the Recycle Bin check behaves similarly, it's not always accurate across different server versions. Thank you for the quick response and your work building this tool!

**Comment by lkitsos** [comment]
Hi,
Replace line 1789 with:
if (!$SMBv1 -or $SMBv1 -eq 'False' -or $SMBv1 -eq $false -or $SMBv1.EnableSMB1Protocol -eq 'False' -or !$SMBv1.EnableSMB1Protocol)

This solved for me the problem i had on Windows Server 2019.
This change only applies to version 6.0.5 i haven't tested on other versions.

**Comment by ClaudioMerola** [comment]
Hi @lkitsos,

Thanks for the fix. I already applied in the script
